Repository Trident-Development/janus-bot, pull requests merged in 2022-08, with the labels that each got.

#3 Card posting on channel is up and running
  README.md
  app.py
  disc/cog.py
  docs/setup.md
  utils/__init__.py
Labels: enhancement

#4 Improve LinkedIn scraping API
  job_boards_scrapers/__init__.py
  job_boards_scrapers/base.py
  job_boards_scrapers/glassdoor.py
  job_boards_scrapers/linkedin.py
Labels: bug

#10 Improve interface for linkedin job scraping
  disc/cog.py
  job_boards_scrapers/linkedin.py
  utils/validator.py
Labels: bug, enhancement

#11 Create apply now button
  disc/cog.py
Labels: enhancement

#12 Adds view profile feature
  config/default_settings.py
  disc/cog.py
  requirements.txt
Labels: enhancement
